artifacts_root: artifacts

# DATA CORRECTION 
data_correction: 
      # input 
      train_raw_data_path: artifacts/data_ingestion/train_data.pkl

      # output
      root_dir: artifacts/data_correction_${C}
      preprocessor_path: artifacts/data_correction_${C}/preprocessor.pkl
      data_path: artifacts/data_correction_${C}/data.pkl
      train_data_path: artifacts/data_correction_${C}/train_data.pkl
      val_data_path: artifacts/data_correction_${C}/val_data.pkl
      class_names_path: artifacts/data_correction_${C}/class_names.pkl

# DATA TRANSFORMATION
data_transformation:
      # input 
      train_data_path: artifacts/data_correction_${C}/train_data.pkl
      val_data_path: artifacts/data_correction_${C}/val_data.pkl

      # output
      root_dir: artifacts/data_transformation_${P}
      preprocessor_path: artifacts/data_transformation_${P}/preprocessor.pkl
      train_features_path: artifacts/data_transformation_${P}/train_features.pkl
      train_target_path: artifacts/data_transformation_${P}/train_target.pkl
      val_features_path: artifacts/data_transformation_${P}/val_features.pkl
      val_target_path: artifacts/data_transformation_${P}/val_target.pkl

# MODEL TRAINING
model_trainer:
      # input
      train_feature_path: artifacts/data_transformation_${P}/train_features.pkl
      train_target_path: artifacts/data_transformation_${P}/train_target.pkl
      val_feature_path: artifacts/data_transformation_${P}/val_features.pkl
      val_target_path: artifacts/data_transformation_${P}/val_target.pkl
      class_names_path: artifacts/data_correction_${C}/class_names.pkl

      # output
      root_dir: artifacts/model_trainer/${T}
      best_model_path: artifacts/model_trainer/${T}/best_model.pkl
      results_path: artifacts/model_trainer/${T}/results.txt
      list_monitor_components_path: artifacts/model_trainer/list_monitor_components.pkl

# TEST DATA CORRECTION 
test_data_correction: 
      # input 
      test_raw_data_path: artifacts/data_ingestion/test_data.pkl
      preprocessor_path: artifacts/data_correction_${CE}/preprocessor.pkl

      # output
      root_dir: artifacts/test_data_correction
      test_data_path: artifacts/test_data_correction/test_data.pkl


# MODEL_EVALUATION
model_evaluation:
      # input
      test_data_path: artifacts/test_data_correction/test_data.pkl
      preprocessor_path: artifacts/data_transformation_${PE}/preprocessor.pkl
      model_path: artifacts/model_trainer/${E}/best_model.pkl
      class_names_path: artifacts/data_correction/class_names.pkl

      # output
      root_dir: artifacts/model_evaluation/${E}
      results_path: artifacts/model_evaluation/${E}/results.txt
