def get_params_transform_list_to_1_value(param_grid):
    values = [item[0] for item in param_grid.values()]
    return dict(zip(param_grid.keys(), values))


param_grid = {
    "C": [1],
    "A": [2],
}

print(get_params_transform_list_to_1_value(param_grid))

a = [
    "HeightInMeters_num",
    "WeightInKilograms_num",
    "PhysicalHealthDays_numcat",
    "MentalHealthDays_numcat",
    "SleepHours_numcat",
    "PhysicalActivities_bin",
    "HadAngina_bin",
    "HadStroke_bin",
    "HadAsthma_bin",
    "HadSkinCancer_bin",
    "HadCOPD_bin",
    "HadDepressiveDisorder_bin",
    "HadKidneyDisease_bin",
    "HadArthritis_bin",
    "DeafOrHardOfHearing_bin",
    "BlindOrVisionDifficulty_bin",
    "DifficultyConcentrating_bin",
    "DifficultyWalking_bin",
    "DifficultyDressingBathing_bin",
    "DifficultyErrands_bin",
    "AlcoholDrinkers_bin",
    "FluVaxLast12_bin",
    "PneumoVaxEver_bin",
    "State_nom",
    "Sex_nom",
    "RemovedTeeth_nom",
    "HadDiabetes_nom",
    "AgeCategory_nom",
    "TetanusLast10Tdap_nom",
    "GeneralHealth_ord",
    "LastCheckupTime_ord",
    "SmokerStatus_ord",
    "ECigaretteUsage_ord",
]


a = [
    "HeightInMeters_num",
    "WeightInKilograms_num",
    "PhysicalHealthDays_numcat",
    "MentalHealthDays_numcat",
    "SleepHours_numcat",
    "PhysicalActivities_bin",
    "HadAngina_bin",
    "HadStroke_bin",
    "HadAsthma_bin",
    "HadSkinCancer_bin",
    "HadCOPD_bin",
    "HadDepressiveDisorder_bin",
    "HadKidneyDisease_bin",
    "HadArthritis_bin",
    "DeafOrHardOfHearing_bin",
    "BlindOrVisionDifficulty_bin",
    "DifficultyConcentrating_bin",
    "DifficultyWalking_bin",
    "DifficultyDressingBathing_bin",
    "DifficultyErrands_bin",
    "AlcoholDrinkers_bin",
    "FluVaxLast12_bin",
    "PneumoVaxEver_bin",
    "State_nom",
    "Sex_nom",
    "RemovedTeeth_nom",
    "HadDiabetes_nom",
    "AgeCategory_nom",
    "TetanusLast10Tdap_nom",
    "GeneralHealth_ord",
    "LastCheckupTime_ord",
    "SmokerStatus_ord",
    "ECigaretteUsage_ord",
]


a = [
    "HeightInMeters_num",
    "WeightInKilograms_num",
    "PhysicalHealthDays_numcat",
    "MentalHealthDays_numcat",
    "SleepHours_numcat",
    "PhysicalActivities_bin",
    "HadAngina_bin",
    "HadStroke_bin",
    "HadAsthma_bin",
    "HadSkinCancer_bin",
    "HadCOPD_bin",
    "HadDepressiveDisorder_bin",
    "HadKidneyDisease_bin",
    "HadArthritis_bin",
    "DeafOrHardOfHearing_bin",
    "BlindOrVisionDifficulty_bin",
    "DifficultyConcentrating_bin",
    "DifficultyWalking_bin",
    "DifficultyDressingBathing_bin",
    "DifficultyErrands_bin",
    "AlcoholDrinkers_bin",
    "FluVaxLast12_bin",
    "PneumoVaxEver_bin",
    "RemovedTeeth_nom",
    "HadDiabetes_nom",
    "AgeCategory_nom",
    "TetanusLast10Tdap_nom",
    "GeneralHealth_ord",
    "LastCheckupTime_ord",
    "SmokerStatus_ord",
    "ECigaretteUsage_ord",
]
