# COMMON
scoring: accuracy
target_score: 0.99

# DATA CORRECTION
data_correction: 
      name: dc2  # id của data correction 
      do_run: t # t: true, f: false

# DATA TRANSFORMATION
data_transformation: 
      number: dt3  # id của data_transformation
      do_smote: f # t: true, f: false
      list_after_feature_transformer:
            - PolynomialFeatures(degree=2, include_bias=False)


# MODEL TRAINING  
model_trainer: 
      model_name: model15 
      model_training_type: m  # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal, m: many models

      # Cần cho model_training_type = rcv, gcv, r, g
      base_model: XGBClassifier(random_state=42)
      n_iter: 1 # số tổ hợp chọn khi chạy random search
      param_grid:
            n_estimators: 100-200
            max_depth: 10-20
            reg_alpha: 0-1
            reg_lambda: 1-5
            learning_rate: 10
            subsample: 0.9-1
            colsample_bytree: 0.9-1

      # Càn cho model_training_type = m
      models: 
            - LGBMClassifier(n_estimators=300, max_depth=25, reg_alpha = 1, reg_lambda=5)
            - LGBMClassifier(n_estimators=300, max_depth=25, reg_alpha = 5, reg_lambda=5)
                  
# MODEL EVALUATION
model_evaluation: 
      data_correction_name: dc1
      data_transformation_no: dt1
      model_name: XGB_12

# MONITOR PLOT
monitor_plotter:
      monitor_plot_html_path: "artifacts/model_trainer/monitor_plot.html"
      monitor_plot_fig_path: "artifacts/model_trainer/monitor_plot_fig.pkl"
      target_val_value: 99
      max_val_value: 100
      dtick_y_value: 5
